In [15]:
import numpy as np

scalar = 3.7

array = np.array([1,2,3,4,5,6,7,8,9])


print("\nSine:")
print(np.sin(array))

print("\nCoine:")
print(np.cos(array))

print("\nTangent:")
print(np.tan(array))



Sine:
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]

Coine:
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]

Tangent:
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]


In [16]:
matrix = np.array([[1, 2], [3, 4]])

sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

exp_values = np.exp(matrix)
log_values = np.log(matrix)

abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

rem_values = np.remainder(matrix, 2)

round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[1 2]
 [3 4]]

sin:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]

cos:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]

tan:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]

asine:
 [[0.25268026 0.52359878]
 [0.84806208 1.57079633]]

acosine:
 [[1.31811607 1.04719755]
 [0.72273425 0.        ]]

atangent:
 [[0.78539816 1.10714872]
 [1.24904577 1.32581766]]

exp:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

log (natural):
 [[0.         0.69314718]
 [1.09861229 1.38629436]]

abs:
 [[1 2]
 [3 4]]

sqrt:
 [[1.         1.41421356]
 [1.73205081 2.        ]]

rem (remainder when divided by 2):
 [[1 0]
 [1 0]]

round:
 [[1 2]
 [3 4]]

floor:
 [[1. 2.]
 [3. 4.]]

ceil:
 [[1. 2.]
 [3. 4.]]


In [17]:
matrix = np.array([[1, 2], [3, 4],[5,6]])

sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

exp_values = np.exp(matrix)
log_values = np.log(matrix)

abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

rem_values = np.remainder(matrix, 2)

round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[1 2]
 [3 4]
 [5 6]]

sin:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155 ]]

cos:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]
 [ 0.28366219  0.96017029]]

tan:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]
 [-3.38051501 -0.29100619]]

asine:
 [[0.16744808 0.33983691]
 [0.52359878 0.72972766]
 [0.98511078 1.57079633]]

acosine:
 [[1.40334825 1.23095942]
 [1.04719755 0.84106867]
 [0.58568554 0.        ]]

atangent:
 [[0.78539816 1.10714872]
 [1.24904577 1.32581766]
 [1.37340077 1.40564765]]

exp:
 [[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]
 [148.4131591  403.42879349]]

log (natural):
 [[0.         0.69314718]
 [1.09861229 1.38629436]
 [1.60943791 1.79175947]]

abs:
 [[1 2]
 [3 4]
 [5 6]]

sqrt:
 [[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]

rem (remainder when divided by 2):
 [[1 0]
 [1 0]
 [1 0]]

round:
 [[1 2]
 [3 4]
 [5 6]]

floor:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

ceil:
 [[1. 2

In [ ]:
matrix = np.array([[3, 1, 4], [1, 5, 9]])

max_value = np.max(matrix)
max_index = np.argmax(matrix)

min_value = np.min(matrix)
min_index = np.argmin(matrix)

matrix_shape = matrix.shape

sorted_matrix_rows = np.sort(matrix, axis=1)
sorted_matrix_cols = np.sort(matrix, axis=0)


sum_values = np.sum(matrix)

prod_values = np.prod(matrix)

median_value = np.median(matrix)

mean_value = np.mean(matrix)

std_dev = np.std(matrix)

print("Matrix:\n", matrix)
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Shape of matrix:", matrix_shape)
print("Sorted matrix (rows):\n", sorted_matrix_rows)
print("Sorted matrix (cols):\n", sorted_matrix_cols)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)
